static: static/bootstrap static/mustache

static/bootstrap:
	mkdir -p static/bootstrap
	mkdir -p static/bootstrap/css
	mkdir -p static/bootstrap/js
	cp ./node_modules/bootstrap/dist/css/{bootstrap.css,bootstrap.min.css} ./static/bootstrap/css/
	cp ./node_modules/bootstrap/dist/js/{bootstrap.js,bootstrap.min.js} ./static/bootstrap/js/

static/mustache:
	mkdir -p static/mustache
	mkdir -p static/mustache/js
	cp ./node_modules/mustache/{mustache.min.js,mustache.mjs} ./static/mustache/js/
